export const USUARIO_TYPES = {
    SUCCESS: 'USUARIO_TYPES_SUCCESS',
};

export const LOGIN_TYPE = {
    LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
    AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
    LOGOUT_SUCCESSFUL: 'LOGOUT_SUCCESSFUL',
    LOGIN_SUCCESSFUL_MICROSOFT: "LOGIN_SUCCESSFUL_MICROSOFT"
}

export const EMPRESA_TYPE = {
    SUCCESS: "EMPRESA_TYPE_SUCCESS"
}

export const SIG_TYPE = {
    ADD_BREADCRUMB: "ADD_BREADCRUMB",
    CLEAR_BREADCRUMB: "CLEAR_BREADCRUMB",
    SET_BREADCRUMB: "SET_BREADCRUMB"
}